name: Build Changelog # Workflow name displayed on GitHub

on:
  workflow_dispatch:
    branches:
      - '*.x'

jobs:
   new-release:
    runs-on: ubuntu-latest
    steps:

      - name: Clone sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          token: ${{ secrets.MY_PAT }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Build Changelog
        run: |
          git config --local user.email "jaymeh@users.noreply.github.com"
          git config --local user.name "Jamie Sykes"
          composer run-script release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_PAT }}
          branch: ${{ github.ref }}
          tags: true
