name: Conventional Commits

on:
  pull_request:
    branches: [ 1.x, 2.x ]

jobs:
  build:
    name: Ensure Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.5